name: Build iOS App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: xcode-27

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show environment
        run: |
          uname -m
          xcodebuild -version
          swift --version

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Show project schemes
        run: |
          xcodebuild \
            -project VPNLiveIndicator.xcodeproj \
            -list

      - name: Build without signing
        run: |
          xcodebuild \
            -project VPNLiveIndicator.xcodeproj \
            -scheme VPNLiveIndicator \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            build

      - name: Create unsigned IPA
        run: |
          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/VPNLiveIndicator.app Payload/
          zip -r VPNLiveIndicator-unsigned.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: VPNLiveIndicator-unsigned
          path: VPNLiveIndicator-unsigned.ipa
